import markdown
import os
import webbrowser
from datetime import datetime

# Configuration
MD_FILE = r'C:\Users\khair\.gemini\antigravity\brain\f500f753-5c2b-42e5-95e6-04d3680c6350\explanation_tabm_training.md'
OUTPUT_HTML = r'd:\op_ecom\tabm_training_deep_dive.html'

# Professional CSS Styling
CSS_STYLE = """
<style>
    :root {
        --primary-color: #1a73e8;
        --secondary-color: #5f6368;
        --bg-color: #ffffff;
        --text-color: #202124;
        --border-color: #dadce0;
        --code-bg: #f8f9fa;
        --accent-color: #e8f0fe;
    }
    
    body {
        font-family: 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
        line-height: 1.6;
        color: var(--text-color);
        max-width: 900px;
        margin: 0 auto;
        padding: 40px;
        background-color: var(--bg-color);
    }
    
    header {
        border-bottom: 3px solid var(--primary-color);
        margin-bottom: 30px;
        padding-bottom: 10px;
    }
    
    h1 { color: var(--primary-color); font-size: 2.5em; margin-bottom: 0.2em; }
    h2 { color: var(--primary-color); border-bottom: 1px solid var(--border-color); padding-bottom: 5px; margin-top: 40px; }
    h3 { color: #3c4043; margin-top: 25px; }
    
    p, li { font-size: 1.1em; margin-bottom: 15px; }
    
    code {
        background-color: var(--code-bg);
        padding: 2px 5px;
        border-radius: 4px;
        font-family: 'Consolas', 'Monaco', monospace;
        font-size: 0.95em;
    }
    
    table {
        width: 100%;
        border-collapse: collapse;
        margin: 25px 0;
        font-size: 1em;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.05);
    }
    
    th, td {
        padding: 12px 15px;
        text-align: left;
        border-bottom: 1px solid var(--border-color);
    }
    
    th {
        background-color: var(--accent-color);
        color: var(--primary-color);
        font-weight: bold;
    }
    
    tr:hover { background-color: #f1f3f4; }
    
    .footer {
        margin-top: 50px;
        padding-top: 20px;
        border-top: 1px solid var(--border-color);
        font-size: 0.9em;
        color: var(--secondary-color);
        text-align: center;
    }
    
    blockquote {
        border-left: 5px solid var(--primary-color);
        background: var(--accent-color);
        margin: 20px 0;
        padding: 10px 20px;
        font-style: italic;
    }
    
    @media print {
        body { padding: 0; }
        .no-print { display: none; }
    }
</style>
"""

def generate_report():
    if not os.path.exists(MD_FILE):
        print(f"Error: {MD_FILE} not found.")
        return

    with open(MD_FILE, 'r', encoding='utf-8') as f:
        md_content = f.read()

    # Convert Markdown to HTML
    html_content = markdown.markdown(md_content, extensions=['extra', 'codehilite', 'tables'])

    # Assemble final HTML
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    full_html = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>TabM Training Deep Dive Report</title>
        {CSS_STYLE}
    </head>
    <body>
        <header>
            <p style="text-align: right; margin: 0; color: #5f6368;">Deep Learning Training Phase</p>
        </header>
        
        {html_content}
        
        <div class="footer">
            <p>Generated by Antigravity AI on {now}</p>
            <p>E-Commerce Out-of-Distribution Detection Project</p>
        </div>
        
        <div class="no-print" style="position: fixed; bottom: 20px; right: 20px;">
            <button onclick="window.print()" style="background: #1a73e8; color: white; border: none; padding: 10px 20px; border-radius: 5px; cursor: pointer; font-size: 16px; box-shadow: 0 2px 5px rgba(0,0,0,0.2);">
                Export to PDF
            </button>
        </div>
    </body>
    </html>
    """

    with open(OUTPUT_HTML, 'w', encoding='utf-8') as f:
        f.write(full_html)

    print(f"Report generated successfully: {OUTPUT_HTML}")
    webbrowser.open('file://' + os.path.abspath(OUTPUT_HTML))

if __name__ == "__main__":
    generate_report()
