import markdown
import os
import webbrowser
from datetime import datetime

# Configuration
MD_FILE = r'C:\Users\khair\.gemini\antigravity\brain\f500f753-5c2b-42e5-95e6-04d3680c6350\explanation_model2_training.md'
OUTPUT_HTML = r'd:\op_ecom\model2_training_deep_dive.html'

# Professional CSS Styling
CSS_STYLE = """
<style>
    :root {
        --primary-color: #2c3e50;
        --secondary-color: #27ae60;
        --accent-color: #2980b9;
        --bg-color: #ffffff;
        --text-color: #2c3e50;
        --border-color: #ecf0f1;
        --code-bg: #fdf6e3;
    }
    
    body {
        font-family: 'Inter', -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
        line-height: 1.6;
        color: var(--text-color);
        max-width: 950px;
        margin: 0 auto;
        padding: 50px;
        background-color: var(--bg-color);
    }
    
    header {
        border-bottom: 4px solid var(--secondary-color);
        margin-bottom: 40px;
        padding-bottom: 20px;
    }
    
    h1 { color: var(--primary-color); font-size: 2.8em; margin-bottom: 0.1em; letter-spacing: -1px; }
    h2 { color: var(--secondary-color); border-bottom: 2px solid var(--border-color); padding-bottom: 8px; margin-top: 50px; font-weight: 600; }
    h3 { color: var(--accent-color); margin-top: 30px; font-size: 1.4em; }
    
    p, li { font-size: 1.15em; margin-bottom: 18px; color: #444; }
    
    code {
        background-color: var(--code-bg);
        padding: 3px 6px;
        border-radius: 6px;
        font-family: 'Fira Code', 'Courier New', monospace;
        font-size: 0.9em;
        border: 1px solid #eee8d5;
    }
    
    table {
        width: 100%;
        border-collapse: separate;
        border-spacing: 0;
        margin: 35px 0;
        border-radius: 12px;
        overflow: hidden;
        box-shadow: 0 4px 15px rgba(0,0,0,0.08);
    }
    
    th, td {
        padding: 16px 20px;
        text-align: left;
        border-bottom: 1px solid var(--border-color);
    }
    
    th {
        background-color: var(--primary-color);
        color: #ecf0f1;
        font-weight: 500;
        text-transform: uppercase;
        font-size: 0.85em;
        letter-spacing: 1px;
    }
    
    tr:last-child td { border-bottom: none; }
    tr:nth-child(even) { background-color: #f9f9f9; }
    tr:hover { background-color: #f5f5f5; }
    
    .footer {
        margin-top: 70px;
        padding-top: 30px;
        border-top: 2px solid var(--border-color);
        font-size: 0.95em;
        color: #7f8c8d;
        text-align: center;
    }
    
    blockquote {
        border-left: 6px solid var(--secondary-color);
        background: #f1fff4;
        margin: 25px 0;
        padding: 15px 30px;
        font-style: italic;
        border-radius: 0 8px 8px 0;
    }

    .highlight {
        color: var(--secondary-color);
        font-weight: bold;
    }
    
    @media print {
        body { padding: 0; }
        .no-print { display: none; }
    }
</style>
"""

def generate_report():
    if not os.path.exists(MD_FILE):
        print(f"Error: {MD_FILE} not found.")
        return

    with open(MD_FILE, 'r', encoding='utf-8') as f:
        md_content = f.read()

    # Convert Markdown to HTML
    html_content = markdown.markdown(md_content, extensions=['extra', 'codehilite', 'tables'])

    # Assemble final HTML
    now = datetime.now().strftime("%B %d, %Y - %H:%M:%S")
    full_html = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Model 2 TCN Training Audit</title>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=Fira+Code&display=swap" rel="stylesheet">
        {CSS_STYLE}
    </head>
    <body>
        <header>
            <p style="text-align: right; margin: 0; font-weight: 500; color: #95a5a6;">TCN Temporal Training</p>
        </header>
        
        {html_content}
        
        <div class="footer">
            <p><strong>OP-ECOM Model 2 Pipeline Audit</strong></p>
            <p>Generated by Antigravity AI on {now}</p>
        </div>
        
        <div class="no-print" style="position: fixed; bottom: 30px; right: 30px;">
            <button onclick="window.print()" style="background: var(--secondary-color); color: white; border: none; padding: 12px 25px; border-radius: 8px; cursor: pointer; font-size: 17px; font-weight: 600; box-shadow: 0 4px 10px rgba(0,0,0,0.2); transition: transform 0.2s;">
                Print to PDF
            </button>
        </div>
    </body>
    </html>
    """

    with open(OUTPUT_HTML, 'w', encoding='utf-8') as f:
        f.write(full_html)

    print(f"Report generated successfully: {OUTPUT_HTML}")
    webbrowser.open('file://' + os.path.abspath(OUTPUT_HTML))

if __name__ == "__main__":
    generate_report()
